trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - terraform
      - pipelines/terraform-*.yaml
      - infra-pipeline.yaml

pr:
  - master

parameters:
  - name: local_environments
    type: object
    default:
      - name: wanda
        address: "192.168.80.11"
  - name: environment_components
    type: object
    default:
      - deployment: dns
        environment: dns
        component: dns
        serviceConnection: "MSDN Sub"
        storageAccount: dns175090c1a7c944d1
        destroy: false
        deploy: true
        dependsOn: []
      - deployment: az_prod_gameserver
        environment: az-prod
        component: gameserver
        serviceConnection: "MSDN Sub"
        storageAccount: gamec96560353b1a4d1a
        destroy: false
        deploy: true
        dependsOn: []
      - deployment: k8s_infra
        environment: wanda
        component: k8s
        serviceConnection: "MSDN Sub"
        storageAccount: wanda1a85dd9018454b4
        destroy: false
        deploy: true
        local: true
        dependsOn:
          - CheckEnvIsOnline_wanda
      - deployment: migration
        environment: wanda
        component: migration
        serviceConnection: "MSDN Sub"
        storageAccount: wanda1a85dd9018454b4
        destroy: false
        deploy: true
        local: true
        dependsOn:
          - CheckEnvIsOnline_wanda
      - deployment: pteronode
        environment: wanda
        component: pteronode
        serviceConnection: "MSDN Sub"
        storageAccount: wanda1a85dd9018454b4
        destroy: false
        deploy: true
        local: true
        dependsOn:
          - CheckEnvIsOnline_wanda

variables:
  - name: agentImage
    value: ubuntu-20.04
  - name: terraformVersion
    value: 1.3.6

stages:
  - ${{ each env in parameters.local_environments }}:
      - stage: CheckEnvIsOnline_${{ env.name }}
        dependsOn: []
        jobs:
          - job: CheckEnvIsOnline_${{ env.name }}
            pool:
              name: SelfHostedDocker
            steps:
              - script: |
                  if nc -z ${{ env.address }} 22 2>/dev/null; then
                    echo "${{ env.address }} ✓"
                    echo "##vso[task.setvariable variable=online;isOutput=true]true"
                  else
                    echo "${{ env.address }} ✗"
                    echo "##vso[task.setvariable variable=online;isOutput=true]false"
                  fi
                name: checkOnline
  - ${{ each deployment in parameters.environment_components }}:
      - stage: ${{ deployment.deployment }}
        dependsOn: ${{ deployment.dependsOn }}
        jobs:
          - ${{ if eq(deployment.local, true) }}:
            - job: Test
              pool:
                name: SelfHostedDocker
              steps:
                - script: |
                    echo "$[stageDependencies.CheckEnvIsOnline_${{ deployment.environment }}.CheckEnvIsOnline_${{ deployment.environment }}.outputs['checkOnline.online']]"
          - job: TerraformPlan
            ${{ if eq(deployment.local, true) }}:
              condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'), eq(dependencies.CheckEnvIsOnline_${{ deployment.environment }}.outputs['CheckEnvIsOnline_${{ deployment.environment }}.online'], 'true'))
            ${{ else }}:  
              condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
            pool:
              ${{ if eq(deployment.local, true) }}:
                name: SelfHostedDocker
              ${{ else }}:
                vmImage: $(agentImage)
            steps:
              - template: pipelines/terraform-init.yaml
                parameters:
                  terraformVersion: $(terraformVersion)
                  storageAccount: ${{ deployment.storageAccount}}
                  workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                  azureRmKey: ${{ deployment.deployment }}
                  ${{ if eq(deployment.local, true) }}:
                    downloadUrl: "https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_arm64.zip"
              - template: pipelines/terraform-plan.yaml
                parameters:
                  serviceConnection: ${{ deployment.serviceConnection }}
                  workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                  variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/${{ deployment.environment }}/${{ deployment.environment }}.tfvars
          - job: TerraformApply
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            pool:
              ${{ if eq(deployment.local, true) }}:
                name: SelfHostedDocker
              ${{ else }}:
                vmImage: $(agentImage)
            steps:
              - template: pipelines/terraform-init.yaml
                parameters:
                  terraformVersion: $(terraformVersion)
                  storageAccount: ${{ deployment.storageAccount}}
                  workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                  azureRmKey: ${{ deployment.deployment }}
                  ${{ if eq(deployment.local, true) }}:
                    downloadUrl: "https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_arm64.zip"
              - ${{ if eq(deployment.destroy, true) }}:
                  - template: pipelines/terraform-destroy.yaml
                    parameters:
                      serviceConnection: ${{ deployment.serviceConnection }}
                      workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                      variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/${{ deployment.environment }}/${{ deployment.environment }}.tfvars
              - ${{ if eq(deployment.deploy, true) }}:
                  - template: pipelines/terraform-apply.yaml
                    parameters:
                      serviceConnection: ${{ deployment.serviceConnection }}
                      workingDirectory: $(System.DefaultWorkingDirectory)/terraform/components/${{ deployment.component }}
                      variableFilePath: $(System.DefaultWorkingDirectory)/terraform/environments/${{ deployment.environment }}/${{ deployment.environment }}.tfvars
                      ${{ if eq(deployment.local, true) }}:
                        parallelism: 2
